=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'POST', '/marketplace-api/v1/access-token', controller_name: 'autorizao', action_name: 'access_token_post'
  add_swagger_route 'GET', '/marketplace-api/v1/search', controller_name: 'busca', action_name: 'search_get'
  add_swagger_route 'GET', '/marketplace-api/v1/carts/me', controller_name: 'carrinho', action_name: 'carts_me_get'
  add_swagger_route 'POST', '/marketplace-api/v1/carts/me/items', controller_name: 'carrinho', action_name: 'carts_me_items_post'
  add_swagger_route 'DELETE', '/marketplace-api/v1/carts/me/items/{skuId}', controller_name: 'carrinho', action_name: 'carts_me_items_sku_id_delete'
  add_swagger_route 'PUT', '/marketplace-api/v1/carts/me/items/{skuId}', controller_name: 'carrinho', action_name: 'carts_me_items_sku_id_put'
  add_swagger_route 'PUT', '/marketplace-api/v1/carts/me/shipping', controller_name: 'carrinho', action_name: 'carts_me_shipping_put'
  add_swagger_route 'GET', '/marketplace-api/v1/carts/me/shipping/rates', controller_name: 'carrinho', action_name: 'carts_me_shipping_rates_get'
  add_swagger_route 'GET', '/marketplace-api/v1/categories', controller_name: 'categoria', action_name: 'categories_get'
  add_swagger_route 'POST', '/marketplace-api/v1/purchases/authorize', controller_name: 'compra', action_name: 'purchases_authorize_post'
  add_swagger_route 'POST', '/marketplace-api/v1/purchases/{id}/confirm', controller_name: 'compra', action_name: 'purchases_id_confirm_post'
  add_swagger_route 'GET', '/marketplace-api/v1/purchases/{id}', controller_name: 'compra', action_name: 'purchases_id_get'
  add_swagger_route 'GET', '/marketplace-api/v1/purchases/me', controller_name: 'compra', action_name: 'purchases_me_get'
  add_swagger_route 'POST', '/marketplace-api/v1/purchases', controller_name: 'compra', action_name: 'purchases_post'
  add_swagger_route 'GET', '/marketplace-api/v1/addresses/{zipCode}', controller_name: 'endereo', action_name: 'addresses_zip_code_get'
  add_swagger_route 'GET', '/marketplace-api/v1/stores', controller_name: 'lojas', action_name: 'stores_get'
  add_swagger_route 'GET', '/marketplace-api/v1/participants/me/balance', controller_name: 'participante', action_name: 'participants_me_balance_get'
  add_swagger_route 'GET', '/marketplace-api/v1/participants/me/extract', controller_name: 'participante', action_name: 'participants_me_extract_get'
  add_swagger_route 'GET', '/marketplace-api/v1/participants/me', controller_name: 'participante', action_name: 'participants_me_get'
  add_swagger_route 'PUT', '/marketplace-api/v1/participants/me/password', controller_name: 'participante', action_name: 'participants_me_password_put'
  add_swagger_route 'PUT', '/marketplace-api/v1/participants/me', controller_name: 'participante', action_name: 'participants_me_put'
  add_swagger_route 'POST', '/marketplace-api/v1/participants', controller_name: 'participante', action_name: 'participants_post'
  add_swagger_route 'POST', '/marketplace-api/v1/participants/{username}/password-reset', controller_name: 'participante', action_name: 'participants_username_password_reset_post'
  add_swagger_route 'GET', '/marketplace-api/v1/products/{productSKUId}', controller_name: 'produto', action_name: 'products_product_sku_id_get'
  add_swagger_route 'GET', '/marketplace-api/v1/skus/{id}/availability', controller_name: 'sKU', action_name: 'skus_id_availability_get'
  add_swagger_route 'GET', '/marketplace-api/v1/showcases/{showcase_id}', controller_name: 'vitrine', action_name: 'showcases_showcase_id_get'
end
