=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "address".pluralize.to_sym, id: false do |t|
      t.string :street
      t.string :number
      t.string :complement
      t.string :district
      t.string :city
      t.string :state
      t.string :zip_code
      t.string :reference

      t.timestamps
    end

    create_table "address_req".pluralize.to_sym, id: false do |t|
      t.string :street
      t.string :number
      t.string :complement
      t.string :district
      t.string :city
      t.string :state
      t.string :zip_code

      t.timestamps
    end

    create_table "availability".pluralize.to_sym, id: false do |t|
      t.boolean :availability
      t.float :price_from
      t.float :price_for

      t.timestamps
    end

    create_table "balance".pluralize.to_sym, id: false do |t|
      t.float :points_value
      t.float :points_value_onhold
      t.float :total_points_value
      t.float :total_credit_points_value
      t.float :total_debit_points_value

      t.timestamps
    end

    create_table "brand".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "business_error_message".pluralize.to_sym, id: false do |t|
      t.string :code
      t.string :message

      t.timestamps
    end

    create_table "campaign".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "cart".pluralize.to_sym, id: false do |t|
      t.float :price
      t.string :items
      t.string :customer
      t.string :shipping

      t.timestamps
    end

    create_table "cart_item".pluralize.to_sym, id: false do |t|
      t.string :sku_id
      t.string :name
      t.string :category
      t.string :image_url
      t.string :price
      t.integer :quantity
      t.string :vendor

      t.timestamps
    end

    create_table "cart_shipping".pluralize.to_sym, id: false do |t|
      t.string :customer
      t.string :address

      t.timestamps
    end

    create_table "cart_shipping_customer".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :document_number
      t.string :email
      t.date :birth_date
      t.string :gender_type
      t.string :person_type
      t.string :phones

      t.timestamps
    end

    create_table "catalog".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "categories".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug
      t.string :subcategories

      t.timestamps
    end

    create_table "category".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "credit_card_payment".pluralize.to_sym, id: false do |t|
      t.string :brand
      t.string :name
      t.string :number
      t.string :expiration_month
      t.string :expiration_year
      t.string :security_code
      t.float :portions
      t.float :value_points

      t.timestamps
    end

    create_table "email".pluralize.to_sym, id: false do |t|
      t.string :email
      t.string :type

      t.timestamps
    end

    create_table "extract".pluralize.to_sym, id: false do |t|
      t.string :authorization_code
      t.string :date
      t.string :description
      t.float :value_points
      t.string :type

      t.timestamps
    end

    create_table "features".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :value
      t.string :type

      t.timestamps
    end

    create_table "filter_category".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug
      t.integer :quantity
      t.string :subcategories

      t.timestamps
    end

    create_table "items".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :product_id
      t.string :name
      t.string :image_url
      t.string :value_points
      t.string :quantity
      t.string :shipping_estimate

      t.timestamps
    end

    create_table "orders".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :vendor_order_id
      t.string :status
      t.float :value_points
      t.float :products_value_points
      t.float :shipping_value_points
      t.string :items
      t.string :vendor

      t.timestamps
    end

    create_table "participant".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :username
      t.string :document_number
      t.string :rg
      t.date :birth_date
      t.string :persontype
      t.string :gender_type
      t.string :marital_status
      t.string :status
      t.string :emails
      t.string :phones
      t.string :address

      t.timestamps
    end

    create_table "participant_add".pluralize.to_sym, id: false do |t|
      t.string :client_id
      t.string :catalog_id
      t.string :profile_id
      t.string :name
      t.string :document_number
      t.string :rg
      t.string :status
      t.string :username
      t.string :password
      t.string :marital_status
      t.string :person_type
      t.string :gender_type
      t.date :birth_date
      t.string :emails
      t.string :phones
      t.string :address

      t.timestamps
    end

    create_table "participant_result".pluralize.to_sym, id: false do |t|
      t.string :id

      t.timestamps
    end

    create_table "participant_upt".pluralize.to_sym, id: false do |t|
      t.string :client_id
      t.string :catalog_id
      t.string :profile_id
      t.string :name
      t.string :document_number
      t.string :rg
      t.string :status
      t.string :password
      t.string :marital_status
      t.string :person_type
      t.string :gender_type
      t.date :birth_date
      t.string :emails
      t.string :phones
      t.string :address

      t.timestamps
    end

    create_table "password".pluralize.to_sym, id: false do |t|
      t.string :old_password
      t.string :new_password

      t.timestamps
    end

    create_table "payment_brand".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :image_url

      t.timestamps
    end

    create_table "phone".pluralize.to_sym, id: false do |t|
      t.string :area_code
      t.string :number
      t.string :type

      t.timestamps
    end

    create_table "price".pluralize.to_sym, id: false do |t|
      t.float :from
      t.float :_for

      t.timestamps
    end

    create_table "product".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :original_id
      t.string :name
      t.string :image_url
      t.string :vendor
      t.string :category
      t.string :brand

      t.timestamps
    end

    create_table "product_brand".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "product_category".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :subcategories

      t.timestamps
    end

    create_table "product_detail".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :original_id
      t.string :name
      t.string :description
      t.string :sections
      t.string :skus
      t.string :features
      t.string :vendor

      t.timestamps
    end

    create_table "product_detail_vendor".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :logo_type
      t.integer :type

      t.timestamps
    end

    create_table "product_sku_detail".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :original_id
      t.string :status
      t.string :ean
      t.string :images
      t.string :features

      t.timestamps
    end

    create_table "product_search".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :original_id
      t.string :name
      t.string :category
      t.string :brand
      t.string :vendor

      t.timestamps
    end

    create_table "product_subcategory".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "product_vendor".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :logo_type

      t.timestamps
    end

    create_table "purchase".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :date
      t.float :value_points
      t.float :shipping_value_points
      t.string :channel_type
      t.string :orders
      t.string :payments
      t.string :customer
      t.string :campaign
      t.string :catalog

      t.timestamps
    end

    create_table "purchase_add".pluralize.to_sym, id: false do |t|
      t.string :id

      t.timestamps
    end

    create_table "purchase_auth_conversion_rate".pluralize.to_sym, id: false do |t|
      t.string :vendor_id
      t.float :conversion_factor

      t.timestamps
    end

    create_table "purchase_auth_customer".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :document_number
      t.string :rg
      t.string :email
      t.string :person_type
      t.string :gender_type
      t.date :birth_date
      t.string :phones

      t.timestamps
    end

    create_table "purchase_auth_items".pluralize.to_sym, id: false do |t|
      t.string :product_id
      t.string :vendor_sku_id
      t.string :sku_id
      t.string :name
      t.string :quantity
      t.string :category
      t.string :image_url
      t.string :price
      t.string :vendor

      t.timestamps
    end

    create_table "purchase_auth_vendor".pluralize.to_sym, id: false do |t|
      t.string :id

      t.timestamps
    end

    create_table "purchase_authorize".pluralize.to_sym, id: false do |t|
      t.string :channel_type
      t.string :vendor_order_id
      t.string :customer
      t.string :shipping
      t.string :items

      t.timestamps
    end

    create_table "purchase_customer".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :document_number
      t.string :rg
      t.string :email
      t.string :address
      t.string :phones

      t.timestamps
    end

    create_table "purchase_payment".pluralize.to_sym, id: false do |t|
      t.string :transaction_id
      t.string :date
      t.float :value_points
      t.string :type
      t.string :brand
      t.float :installments
      t.float :installments_value

      t.timestamps
    end

    create_table "purchase_post".pluralize.to_sym, id: false do |t|
      t.string :cart_type
      t.string :channel_type
      t.string :credit_card_payment

      t.timestamps
    end

    create_table "request_add_cart_item".pluralize.to_sym, id: false do |t|
      t.string :vendor_id
      t.string :product_sku_id

      t.timestamps
    end

    create_table "request_upd_cart_item".pluralize.to_sym, id: false do |t|
      t.integer :quantity

      t.timestamps
    end

    create_table "sku_images".pluralize.to_sym, id: false do |t|
      t.string :small_image
      t.string :medium_image
      t.string :large_image
      t.float :order

      t.timestamps
    end

    create_table "search".pluralize.to_sym, id: false do |t|
      t.string :products
      t.string :categories
      t.string :brands
      t.string :vendors
      t.float :lower_price
      t.float :higher_price
      t.string :page_index
      t.string :last_page

      t.timestamps
    end

    create_table "sections".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :section_type
      t.string :name
      t.string :slug

      t.timestamps
    end

    create_table "shipping_rates".pluralize.to_sym, id: false do |t|
      t.float :total
      t.string :vendors

      t.timestamps
    end

    create_table "showcase".pluralize.to_sym, id: false do |t|
      t.float :lower_price
      t.float :higher_price
      t.string :products
      t.string :vendors
      t.string :categories
      t.string :brands

      t.timestamps
    end

    create_table "stores".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :logotype
      t.float :priority
      t.string :vendor

      t.timestamps
    end

    create_table "subcategories".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug

      t.timestamps
    end

    create_table "subcategory".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug
      t.integer :quantity

      t.timestamps
    end

    create_table "token".pluralize.to_sym, id: false do |t|
      t.string :access_token
      t.string :refresh_token
      t.string :token_type
      t.integer :expires_in

      t.timestamps
    end

    create_table "vendor".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug
      t.string :logo_type

      t.timestamps
    end

    create_table "vendor_cart".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :type

      t.timestamps
    end

    create_table "vendor_orders".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "vendor_rate".pluralize.to_sym, id: false do |t|
      t.string :id
      t.datetime :delivery_date
      t.float :total

      t.timestamps
    end

    create_table "vendor_search".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :slug

      t.timestamps
    end

    create_table "vendor_stores".pluralize.to_sym, id: false do |t|
      t.string :id

      t.timestamps
    end

    create_table "zip_code_address".pluralize.to_sym, id: false do |t|
      t.string :street_type
      t.string :street
      t.string :district
      t.string :city
      t.string :state

      t.timestamps
    end

  end
end
