=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AutorizaoController < ApplicationController

  def access_token_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
