=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CarrinhoController < ApplicationController

  def carts_me_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_me_items_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_me_items_sku_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_me_items_sku_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_me_shipping_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carts_me_shipping_rates_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
