=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CompraController < ApplicationController

  def purchases_authorize_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def purchases_id_confirm_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def purchases_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def purchases_me_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def purchases_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
