=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class EndereoController < ApplicationController

  def addresses_zip_code_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
