=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ParticipanteController < ApplicationController

  def participants_me_balance_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_me_extract_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_me_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_me_password_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_me_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def participants_username_password_reset_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
