=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class CartShipping < ApplicationRecord
  validates_presence_of :customer
  validates_presence_of :address

end
