=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ParticipantUpt < ApplicationRecord
  validates_presence_of :client_id
  validates_presence_of :catalog_id
  validates_presence_of :profile_id
  validates_presence_of :status
  validates_presence_of :person_type

  serialize :emails, Array
  serialize :phones, Array
end
