=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ProductDetail < ApplicationRecord

  serialize :sections, Array
  serialize :skus, Array
  serialize :features, Array
end
