=begin
Marketplace

API Cloud Loyalty LTM - Webpremios

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class RequestUpdCartItem < ApplicationRecord
  validates_presence_of :quantity

end
